apiVersion: v1
kind: Secret
metadata:
# this is the jenkins id.
  name: "a-test-usernamepass-with-custom-id"
  labels:
# so we know what type it is.
    "jenkins.io/credentials-type": "usernamePassword"
  annotations:
# description - can not be a label as spaces are not allowed
    "jenkins.io/credentials-description" : "credentials from Kubernetes"
    # set ID of the generated credential
    "jenkins.io/credentials-id" : "A_TEST_USERNAMEPASS_WITH_CUSTOM_ID"
type: Opaque
stringData:
  username: myUsername
  password: 'Pa$$word'
